### ISSUE TITLE
v3.0.5 doesn't work on Bolt 3.1.1

### ISSUE THREAD

**Issue by nbehier** [GawainLynch/bolt-extension-rssfeed#15] opened 2016-11-21 19:52 UTC
Hi, I couldn't do many tests, but when I upgraded `bolt-extension-rssfeed` to v3.0.5 on my Bolt 3.1.1, `/rss/feed.(xml|rss)` leeds me to 404 error page. When I downgraded extension to v3.0.4, `/rss/feed.(xml|rss)` got me my sitewide RSS feeds. Maybe I forgot something when I try to upgrade ?

**Comment by GawainLynch** [comment] 2016-11-21 20:05
Hmm … this is the only commit that went into 3.0.5 — 72832568dafa3a3ed605f22a2d3ffce08bd0e77b

**Comment by nbehier** [comment] 2016-11-21 20:30
YEs… and I do not have some particular routing… weird…

**Comment by werner-freytag** [comment] 2016-11-22 14:08
Found a problem with bolt 3.2.2 in RssFeedController, line 96: 
`$this->config[$contenttypeslug]['content_types']`
doesn't work, because `$contenttypeslug` is null. Replacing it with` 'sitewide'` fixed it.

**Comment by GawainLynch** [comment] 2016-11-22 15:26
Good catch, @werner-freytag :+1: 

Fixed and tagged as v3.0.6

**Comment by nbehier** [comment] 2016-11-23 10:54
I installed v3.0.6 and get the same 404 error. Return to v3.0.4 and it works perfectly fine for me. (My website is propulsed by Bolt v3.1.1).

**Comment by GawainLynch** [comment] 2016-11-23 11:19
Sacre blue.

That code is still a bit of a mess that I inherited. I rewrote the whole thing yesterday, and tagged 3.1.0-RC1. Due to something not being correct in Bolt's Extend page version selector you'd need to install `3.1.x-dev` and let me know if that works … :monkey: tests passed here, but it is an internal rewrite so I was just going to give it a day or so before tagging a stable version.

**Comment by GawainLynch** [comment] 2016-11-26 13:07
OK, after some further poking the RC seems to work fine, so I have tagged 3.1.0 as a stable release and I'll re-close this.

Please feel most welcome to reopen if you find this is still not fixed, and I'll get on it again a.s.a.p..

Thanks, as always, for your time and understanding :+1:

**Comment by nbehier** [comment] 2016-11-26 13:47
@GawainLynch I've a good and a bad news… The good one : If I gave you some large money for a work and a deadline, maybe I could be annoyed a little… but there, you give so much of your time for several years on an wonderful community project… Thanks a lot once again !!

The bad news… I gave a try to your new v3.0.1… and got the same error on my config… so came back to v2.0.4. Pretty sure that results from my config… I'll open developer toolbar and will try to understand why default route `/rss/feed.xml` could not be find…

**Comment by GawainLynch** [comment] 2016-11-26 13:50
OK, firing up an install here to see if I can reproduce … do you have a config example that you could share that reproduces the problem as I seem to be missing something in the way you are approaching the configuration versus how I am?

**Comment by nbehier** [comment] 2016-11-26 13:56
When I go to `/rss/feed.xml`, I get 404 error page. The tab `@_rss_feed.extension` from developer toolbar displays that :
```
HTTP status : 404 Not Found
Controller Rss : Feed :: feed
Controller class : Bolt\Extension\Bolt\RssFeed\Controller\RssFeed
Route name : _rss_feed.extension
Has session : yes
```

My `rssfeed.bolt.yml` is :
```
sitewide:
    enabled: true
    feed_records: 10
    feed_template: rss.twig
    content_length: 0
    content_types: [entries]
```

**Comment by GawainLynch** [comment] 2016-11-26 13:58
This is my set up and result
```
sitewide:
    enabled: true
    feed_records: 4
    feed_template: rss.twig
    content_length: 10
    content_types: [entries, pages]
```
![screenshot from 2016-11-26 14-57-18](https://cloud.githubusercontent.com/assets/1427081/20640772/0d4475d0-b3ae-11e6-87c9-4cbd50d7ef21.png)

**Comment by GawainLynch** [comment] 2016-11-26 14:00
With a copy/paste of your config:
![screenshot from 2016-11-26 14-59-59](https://cloud.githubusercontent.com/assets/1427081/20640787/5b38bc56-b3ae-11e6-95d2-df2a68268a88.png)

**Comment by nbehier** [comment] 2016-11-26 14:01
I forgot one file, on my theme, I add `rss.twig` with : 
```
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>{{ app.config.get('general/sitename') }}</title>
        <atom:link href="{{ paths.currenturl }}" rel="self" type="application/rss+xml"/>
        <link>{{ paths.rooturl }}</link>
{% if app.config.get('general/payoff') is defined %}
        <description>{{ app.config.get('general/payoff') }}</description>
{% endif %}
        <language>{{ app.config.get('general/locale')|lower }}</language>

{% for record in records %}
            <item>
                <title>{{ record.title|striptags }}</title>
                <link>{{ paths.hosturl }}{{ record.link }}</link>
                <pubDate>
                    {{ record.datepublish|date("r") }}
                </pubDate>
                <author>{{ app.config.get('general/sitename') }}</author>
                <guid isPermaLink="false">{{ record.contenttype.singular_slug }}/{{ record.id }}</guid>
                <description>
                {%- if content_length == 0 -%}
                    {{ record|rss_safe('teaser, body') }}
                {%- else -%}
                    {{ record|rss_safe('teaser, body', content_length) }} [<a href="{{ paths.hosturl }}{{ record.link }}">Lire la suite…</a>]
                {%- endif -%}
                </description>
{% if record.taxonomy is iterable %}
    {%- for taxonomyname, taxonomy in record.taxonomy %}
        {%- for taxonomyvalue in taxonomy %}
                <category domain="{{ taxonomyname }}"><![CDATA[ {{ taxonomyvalue }} ]]></category>
        {%- endfor %}
    {%- endfor %}
{%- endif %}
{% if record.image is not empty %}
                <image>{{ paths.hosturl }}{{ thumbnail(record.image, 600, 400) }}</image>
                <enclosure url="{{ paths.hosturl }}{{ thumbnail(record.image, 600, 400) }}" type="image/jpeg" />
{% endif %}
            </item>

{% endfor %}
    </channel>
</rss>
```

Could this file get me to 404 error page ?

**Comment by nbehier** [comment] 2016-11-26 14:04
Change file to `rss-back.twig` and still get my 404 page…

**Comment by GawainLynch** [comment] 2016-11-26 14:05
Yeah, using your Twig template mine works OK, without the 404 … Hmmm … this is weird.

**Comment by GawainLynch** [comment] 2016-11-26 14:07
Ha! Found it! If you **only** have sitewide it breaks … fix incoming

**Comment by GawainLynch** [comment] 2016-11-26 15:26
OK … Lets try this again shall we :-D

I have pushed and tagged 3.1.1 and that fixes the use-case that we eventually were both seeing.

Same deal, as I want to see how many times I can close and reopen this one :laughing:

**Closed by GawainLynch** 2016-11-26 15:26 UTC

**Comment by nbehier** [comment] 2016-11-26 15:37
It works like a charm !!! Well done and Thanks a lot !

**Comment by GawainLynch** [comment] 2016-11-26 17:00
Thanks mate!

The upside is that we managed to [find a bug in Bolt](https://github.com/bolt/bolt/issues/6090) as a result of me digging
